Repository NEW-PuppyMode/PuppyMode-Server, pull requests merged in 2025-07, with the labels that each got.

#2 Feat/#1 project setup
  .gitignore
  build.gradle
  src/main/java/com/umc/puppymode2/domain/common/BaseEntity.java
  src/main/java/com/umc/puppymode2/domain/temp/controller/TempController.java
  src/main/java/com/umc/puppymode2/domain/temp/converter/TempConverter.java
  src/main/java/com/umc/puppymode2/domain/temp/dto/TempRequestDTO.java
  src/main/java/com/umc/puppymode2/domain/temp/dto/TempResponseDTO.java
  src/main/java/com/umc/puppymode2/domain/temp/entity/Temp.java
  src/main/java/com/umc/puppymode2/domain/temp/entity/enums/TempStatus.java
  src/main/java/com/umc/puppymode2/domain/temp/repository/TempRepository.java
  src/main/java/com/umc/puppymode2/domain/temp/service/TempCommandService.java
  src/main/java/com/umc/puppymode2/domain/temp/service/TempCommandServiceImpl.java
  src/main/java/com/umc/puppymode2/domain/temp/service/TempQueryService.java
  src/main/java/com/umc/puppymode2/domain/temp/service/TempQueryServiceImpl.java
  src/main/java/com/umc/puppymode2/global/apiPayload/ApiResponse.java
  src/main/java/com/umc/puppymode2/global/apiPayload/code/BaseCode.java
  src/main/java/com/umc/puppymode2/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/umc/puppymode2/global/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/umc/puppymode2/global/apiPayload/code/ReasonDTO.java
  src/main/java/com/umc/puppymode2/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/puppymode2/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/umc/puppymode2/global/config/JpaConfig.java
  src/main/java/com/umc/puppymode2/global/config/SwaggerConfig.java
  src/main/java/com/umc/puppymode2/global/exception/ExceptionAdvice.java
  src/main/java/com/umc/puppymode2/global/exception/GeneralException.java
  src/main/java/com/umc/puppymode2/global/exception/handler/TempHandler.java
  src/main/resources/application.properties
  src/test/java/com/umc/puppymode2/config/TestJpaConfig.java
  src/test/java/com/umc/puppymode2/domain/temp/controller/TempControllerTest.java
  src/test/java/com/umc/puppymode2/domain/temp/converter/TempConverterTest.java
  src/test/java/com/umc/puppymode2/domain/temp/entity/TempTest.java
  src/test/java/com/umc/puppymode2/domain/temp/repository/TempRepositoryTest.java
  src/test/java/com/umc/puppymode2/domain/temp/service/TempCommandServiceTest.java
  src/test/java/com/umc/puppymode2/global/exception/ExceptionAdviceTest.java
  src/test/java/com/umc/puppymode2/integration/TempIntegrationTest.java
Labels: ✨ feature

#7 [FEAT] 카카오 로그인 구현 #3
  build.gradle
  src/main/java/com/umc/puppymode2/domain/user/dto/KakaoTokenResponseDTO.java
  src/main/java/com/umc/puppymode2/domain/user/dto/KakaoUserInfoResponseDTO.java
  src/main/java/com/umc/puppymode2/domain/user/dto/LoginResponseDTO.java
  src/main/java/com/umc/puppymode2/domain/user/entity/SocialAuth.java
  src/main/java/com/umc/puppymode2/domain/user/entity/User.java
  src/main/java/com/umc/puppymode2/domain/user/entity/enums/UserStatus.java
  src/main/java/com/umc/puppymode2/domain/user/repository/SocialAuthRepository.java
  src/main/java/com/umc/puppymode2/domain/user/repository/UserRepository.java
  src/main/java/com/umc/puppymode2/domain/user/service/KakaoAuthService.java
  src/main/java/com/umc/puppymode2/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/puppymode2/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/umc/puppymode2/global/auth/context/SecurityUserContext.java
  src/main/java/com/umc/puppymode2/global/auth/context/UserContext.java
  src/main/java/com/umc/puppymode2/global/auth/controller/KakaoAuthController.java
  src/main/java/com/umc/puppymode2/global/auth/dto/UserAuthInfoDTO.java
  src/main/java/com/umc/puppymode2/global/auth/enums/Provider.java
  src/main/java/com/umc/puppymode2/global/auth/service/UserAuthService.java
  src/main/java/com/umc/puppymode2/global/auth/service/UserAuthServiceImpl.java
  src/main/java/com/umc/puppymode2/global/auth/token/JwtTokenProvider.java
  src/main/java/com/umc/puppymode2/global/config/WebClientConfig.java
  src/main/java/com/umc/puppymode2/global/security/CustomAccessDeniedHandler.java
  src/main/java/com/umc/puppymode2/global/security/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/umc/puppymode2/global/security/JwtAuthenticationFilter.java
  src/main/java/com/umc/puppymode2/global/security/JwtValidationType.java
  src/main/java/com/umc/puppymode2/global/security/SecurityConfig.java
  src/main/java/com/umc/puppymode2/global/security/UserAuthentication.java
Labels: ✨ feature

#11 [FEAT] 목표 관련 API 구현 #9
  src/main/java/com/umc/puppymode2/domain/goal/controller/UserGoalHistoryController.java
  src/main/java/com/umc/puppymode2/domain/goal/converter/UserGoalHistoryConverter.java
  src/main/java/com/umc/puppymode2/domain/goal/dto/GoalInfoResponseDTO.java
  src/main/java/com/umc/puppymode2/domain/goal/dto/GoalPostRequestDTO.java
  src/main/java/com/umc/puppymode2/domain/goal/dto/GoalPostResponseDTO.java
  src/main/java/com/umc/puppymode2/domain/goal/entity/UserGoalHistory.java
  src/main/java/com/umc/puppymode2/domain/goal/repository/UserGoalHistoryRepository.java
  src/main/java/com/umc/puppymode2/domain/goal/service/UserGoalHistoryCommandService.java
  src/main/java/com/umc/puppymode2/domain/goal/service/UserGoalHistoryCommandServiceImpl.java
  src/main/java/com/umc/puppymode2/domain/goal/service/UserGoalHistoryQueryService.java
  src/main/java/com/umc/puppymode2/domain/goal/service/UserGoalHistoryQueryServiceImpl.java
Labels: ✨ feature

#14 [REFACTOR] 온보딩 검사 엔티티 연관관계 수정 #13
  src/main/java/com/umc/puppymode2/domain/onboarding/entity/Puppy.java
  src/main/java/com/umc/puppymode2/domain/onboarding/entity/User.java
Labels: ♻️ refactor

#17 [FEAT] 카카오 유저 탈퇴 (연결끊기) API 구현 #16
  src/main/java/com/umc/puppymode2/domain/user/controller/UserController.java
  src/main/java/com/umc/puppymode2/domain/user/entity/SocialAuth.java
  src/main/java/com/umc/puppymode2/domain/user/entity/User.java
  src/main/java/com/umc/puppymode2/domain/user/repository/SocialAuthRepository.java
  src/main/java/com/umc/puppymode2/domain/user/service/KakaoAuthService.java
  src/main/java/com/umc/puppymode2/domain/user/service/UserCommandService.java
  src/main/java/com/umc/puppymode2/domain/user/service/UserCommandServiceImpl.java
Labels: ✨ feature

#23 [FEAT] 메인 화면 조회 API 구현
  src/main/java/com/umc/puppymode2/domain/puppy/controller/MainController.java
  src/main/java/com/umc/puppymode2/domain/puppy/dto/MainResponseDto.java
  src/main/java/com/umc/puppymode2/domain/puppy/entity/Puppy.java
  src/main/java/com/umc/puppymode2/domain/puppy/entity/PuppyType.java
  src/main/java/com/umc/puppymode2/domain/puppy/repository/PuppyLevelRepository.java
  src/main/java/com/umc/puppymode2/domain/puppy/repository/PuppyRepository.java
  src/main/java/com/umc/puppymode2/domain/puppy/service/MainService.java
  src/main/java/com/umc/puppymode2/domain/puppy/service/MainServiceImpl.java
  src/main/java/com/umc/puppymode2/domain/puppy/service/PuppyNameService.java
  src/main/java/com/umc/puppymode2/domain/puppy/service/PuppyNameServiceImpl.java
  src/main/java/com/umc/puppymode2/domain/user/entity/User.java
  src/main/java/com/umc/puppymode2/domain/user/service/UserNameService.java
  src/main/java/com/umc/puppymode2/domain/user/service/UserNameServiceImpl.java
Labels: ✨ feature

#26 [FEAT] 캘린더 조회 API 구현 #22
  src/main/java/com/umc/puppymode2/domain/calendar/controller/CalendarController.java
  src/main/java/com/umc/puppymode2/domain/calendar/converter/CalendarConverter.java
  src/main/java/com/umc/puppymode2/domain/calendar/dto/CalendarResponseDTO.java
  src/main/java/com/umc/puppymode2/domain/calendar/service/CalendarQueryService.java
  src/main/java/com/umc/puppymode2/domain/calendar/service/CalendarQueryServiceImpl.java
  src/main/java/com/umc/puppymode2/domain/drinkhistory/repository/DrinkHistoryRepository.java
  src/main/java/com/umc/puppymode2/global/apiPayload/code/status/SuccessStatus.java
Labels: ✨ feature

#38 [CICD] cicd.yml 파일 생성 #36
  .github/workflows/cicd.yml
  .gitignore
  src/main/resources/application.yml
Labels: 🚀 ci

#40 [BUG] 조건 브랜치명 수정 #39
  .github/workflows/cicd.yml
Labels: 🐛 bug

#44 [BUG] 규칙에 부합하는 role-session-name 수정 #43
  .github/workflows/cicd.yml
Labels: 🐛 bug
